server:
  port: 80



spring:
  cache:
    jcache:
      config: classpath:ehcache.xml
  jpa:
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/xrapid?autoReconnect=true&useSSL=false
    driverClassName: com.mysql.jdbc.Driver
    username: USERNAME
    password: PASSWORD
